GET http://localhost:4000/api/category/get-by-id/514235e2-4b39-4615-8e58-a18a3b8654e0
Accept: application/json

###
GET http://localhost:4000/api/category/get-all
Accept: application/json

###
GET http://localhost:4000/api/review/get-offer-reviews/4717b023-68c0-47ff-bfc5-bdbc0ee5c1ab
Accept: application/json

###
POST http://localhost:4000/api/review/create
Content-Type: application/json

{
  "rating": 3,
  "text": "good deal",
  "offerId": "4717b023-68c0-47ff-bfc5-bdbc0ee5c1ab"
}
###
PUT http://localhost:4000/api/offer/update/5c521374-1387-43b8-bfb8-297f00b9b8db
Content-Type: application/json

{
  "title": "Оператор для ваших вечеринок",
  "description": "помогу запечатлить ваши счастливые дни. Скидка Постоянникам",
  "images": ["lel", "shpel"],
  "categoryId": "514235e2-4b39-4615-8e58-a18a3b8654e0"
}

###
GET http://localhost:4000/api/offer/find-by-id/e25d8415-527f-48a6-9d8f-77345423df52
Accept: application/json

###
POST http://localhost:4000/api/offer/create
Content-Type: application/json

{
  "title": "test offer",
  "description": "description of test offer",
  "images": ["Img1", "img2"],
  "categoryId": "7e773339-b8d5-4d0d-bad7-2be82d4d1ba8"
}

###
GET http://localhost:4000/api/offer/all
Accept: application/json

###
DELETE http://localhost:4000/api/offer/delete/3
Accept: application/json
