GET https://dev-back-mtifgu-4b74af-193-181-209-95.traefik.me/api/category/get-by-id/514235e2-4b39-4615-8e58-a18a3b8654e0
Accept: application/json

###
GET https://dev-back-mtifgu-4b74af-193-181-209-95.traefik.me/api/category/get-all
Accept: application/json

###
GET https://dev-back-mtifgu-4b74af-193-181-209-95.traefik.me/api/review/get-offer-reviews/4717b023-68c0-47ff-bfc5-bdbc0ee5c1ab
Accept: application/json

###
POST https://dev-back-mtifgu-4b74af-193-181-209-95.traefik.me/api/review/create
Content-Type: application/json

{
  "rating": 3,
  "text": "good deal",
  "offerId": "4717b023-68c0-47ff-bfc5-bdbc0ee5c1ab"
}
###
PUT https://dev-back-mtifgu-4b74af-193-181-209-95.traefik.me/api/offer/update/5c521374-1387-43b8-bfb8-297f00b9b8db
Content-Type: application/json

{
  "title": "Оператор для ваших вечеринок",
  "description": "помогу запечатлить ваши счастливые дни. Скидка Постоянникам",
  "images": ["lel", "shpel"],
  "categoryId": "514235e2-4b39-4615-8e58-a18a3b8654e0"
}

###
GET https://dev-back-mtifgu-4b74af-193-181-209-95.traefik.me/api/offer/find-by-id/8d4af88c-7904-442b-892d-ef92cf9d5a78
Accept: application/json

###
POST https://dev-back-mtifgu-4b74af-193-181-209-95.traefik.me/api/offer/create
Content-Type: application/json

{
  "title": "test2 offer",
  "description": "description of test offer",
  "images": ["Img1", "img2"],
  "categoryId": "5a2d0f06-dee9-495d-aee4-23be6e3b8991"
}

###
GET https://dev-back-mtifgu-4b74af-193-181-209-95.traefik.me/api/offer/all
Accept: application/json

###
DELETE https://dev-back-mtifgu-4b74af-193-181-209-95.traefik.me/api/offer/delete/3
Accept: application/json
